# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
git:
  depth: 150

# In order to get sf installed
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - libgeos-dev
      - libv8-3.14-dev

env:
  global:
  - VCR_TURN_OFF=true

matrix:
  include:
    - os: linux
      r: devel

    - os: linux
      r: release

    - os: linux
      r: oldrel

    - os: osx
      r: release

    - os: osx
      r: oldrel

    - os: osx
      r: devel

  allow_failures:
    - os: linux
      r: devel

    - os: osx
      r: devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

after_failure:
  - ./travis-tool.sh dump_logs
